AllCops:
  TargetRubyVersion: 2.1

inherit_from:
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml

Style/SingleLineBlockParams:
  Enabled: false

# Minitest::Spec uses long blocks to contains the specs, so disable this check
# for the tests.
Metrics/BlockLength:
  Max: 10
  Exclude:
    - './scraped.gemspec'
